# Generated by Django 5.2.17 on 2026-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
