# Generated by Django 5.2.17 on 2026-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
